#!/usr/bin/env python3
"""Split the line from the robot to a target into legs and write a mission_manager waypoint file.

  make_waypoints.py --target 34.059635,-117.821028 --from-ros [--leg 27] [--out waypoints_navtest.yaml]
  make_waypoints.py --target LAT,LON --from LAT,LON ...

Why legs: the global costmap is a 100 x 100 m rolling window (about 50 m reach) and Navfn cannot plan to a goal
outside it, so far targets are reached through intermediate points (mission_manager advances at 2.0 m).
--from-ros reads one /gnss fix (run on the Jetson with the sensors up); it prints the fix status and covariance.
"""
import argparse, math, sys

A, E2 = 6378137.0, 6.69437999014e-3


def radii(lat0):
    s2 = math.sin(math.radians(lat0)) ** 2
    return A / math.sqrt(1 - E2 * s2), A * (1 - E2) / (1 - E2 * s2) ** 1.5


def to_enu(lat, lon, lat0, lon0):
    Rn, Rm = radii(lat0)
    return math.radians(lon - lon0) * Rn * math.cos(math.radians(lat0)), math.radians(lat - lat0) * Rm


def from_enu(e, n, lat0, lon0):
    Rn, Rm = radii(lat0)
    return lat0 + math.degrees(n / Rm), lon0 + math.degrees(e / (Rn * math.cos(math.radians(lat0))))


def legs(start, target, leg_m):
    e, n = to_enu(target[0], target[1], *start)
    dist = math.hypot(e, n)
    k = max(1, math.ceil(dist / leg_m))
    pts = [from_enu(e * i / k, n * i / k, *start) for i in range(1, k + 1)]
    return pts, dist, math.degrees(math.atan2(e, n)) % 360, e, n


def read_gnss(timeout=15.0):
    import rclpy
    from rclpy.node import Node
    from rclpy.qos import qos_profile_sensor_data
    from sensor_msgs.msg import NavSatFix
    rclpy.init()
    node = Node('make_waypoints')
    got = []
    node.create_subscription(NavSatFix, '/gnss', lambda m: got.append(m), qos_profile_sensor_data)
    import time
    t0 = time.time()
    while not got and time.time() - t0 < timeout:
        rclpy.spin_once(node, timeout_sec=0.2)
    node.destroy_node(); rclpy.shutdown()
    if not got:
        sys.exit('no /gnss message within %.0f s (sensors running?)' % timeout)
    m = got[-1]
    return m.latitude, m.longitude, m.status.status, m.position_covariance[0] ** 0.5


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--target', required=True, help='LAT,LON')
    ap.add_argument('--from', dest='frm', help='LAT,LON of the robot')
    ap.add_argument('--from-ros', action='store_true')
    ap.add_argument('--leg', type=float, default=27.0, help='maximum leg length (m)')
    ap.add_argument('--out', default=None)
    a = ap.parse_args()
    tgt = tuple(float(x) for x in a.target.split(','))
    if a.from_ros:
        lat, lon, status, sd = read_gnss()
        print(f'robot fix: {lat:.7f}, {lon:.7f}  (NavSatFix status {status}, horizontal sigma {sd:.2f} m)')
        start = (lat, lon)
    elif a.frm:
        start = tuple(float(x) for x in a.frm.split(','))
    else:
        sys.exit('give --from LAT,LON or --from-ros')
    pts, dist, brg, e, n = legs(start, tgt, a.leg)
    print(f'target is {n:.1f} m north, {e:.1f} m east: {dist:.1f} m, bearing {brg:.0f} deg from north; {len(pts)} leg(s) of at most {a.leg:.0f} m')
    prev = start
    for i, p in enumerate(pts, 1):
        pe, pn = to_enu(p[0], p[1], *prev)
        print(f'  leg {i}: {p[0]:.8f}, {p[1]:.8f}   ({math.hypot(pe, pn):.1f} m)')
        prev = p
    if a.out:
        with open(a.out, 'w') as f:
            f.write('# Generated by make_waypoints.py. Robot start %.7f,%.7f  ->  target %.7f,%.7f (%.1f m, %d legs)\n'
                    % (start + tgt + (dist, len(pts))))
            f.write('# Robot must start facing the target (vx_min = 0: the robot never drives in reverse). RTK FIXED required.\n')
            f.write('waypoints:\n')
            for p in pts:
                f.write('  - {lat: %.8f, lon: %.8f}\n' % p)
        print('wrote', a.out)


if __name__ == '__main__':
    main()
